#/*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#**********************************************************************/
version: '3.3'
services: 
  webui:
    image: ${WEBUI_IMAGE}    
    networks:
      - openamtnetwork
    build:
      context: ./sample-web-ui
      dockerfile: ./Dockerfile
    environment:
      RPS_SERVER: https://${MPS_COMMON_NAME}/rps
      MPS_SERVER: https://${MPS_COMMON_NAME}/mps
      VAULT_SERVER: https://${MPS_COMMON_NAME}/vault
    volumes:
      - ./sample-web-ui/nginx.conf:/etc/nginx/conf.d/default.conf  
  rps:
    image: ${RPS_IMAGE}
    networks:
      - openamtnetwork
    build:
      context: ./rps
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment: 
      RPS_MPS_SERVER: http://mps:3000
  mps:
    image: ${MPS_IMAGE}
    networks:
      - openamtnetwork
    build:
      context: ./mps
      dockerfile: ./Dockerfile
    ports:
      - "${MPSPORT}:4433"
    env_file:
      - .env
    environment: 
      MPS_INSTANCE_NAME: '{{.Task.Name}}'
    volumes:
      - private-volume:/mps-microservice/private
  mpsrouter:
    image: mpsrouter:latest
    environment:
      MPS_CONNECTION_STRING: postgresql://postgresadmin:admin123@db:5432/mpsdb?sslmode=disable
      PORT: ${PORT}
      MPS_PORT: ${MPSWEBPORT}
    build:
      context: ./mps-router
      dockerfile: ./Dockerfile
    networks:
      - openamtnetwork
  db:
    image: postgres
    networks:
      - openamtnetwork
    restart: always
    environment:
      POSTGRES_DB: rpsdb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes: 
      - ./data:/docker-entrypoint-initdb.d
  vault:
    image: "vault"
    networks:
      - openamtnetwork
    ports: 
      - "8200:8200"
    environment: 
      VAULT_DEV_ROOT_TOKEN_ID: ${RPS_VAULT_TOKEN}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add: 
      - IPC_LOCK
  kong:
    image: kong:2.3
    healthcheck:
      test:
        - CMD
        - nc
        - -z
        - localhost
        - "8443"
      retries: 10
    command:
      - "kong"
      - "start"
      - "--vv"
    environment:
      - KONG_DATABASE=off
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
      - KONG_NGINX_DAEMON=off
      - KONG_DECLARATIVE_CONFIG=/home/kong/kong.yml
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_DNS_ORDER=LAST,A,CNAME
      - KONG_UPSTREAM_KEEPALIVE_POOL_SIZE=0
    networks:
      - openamtnetwork
    volumes:
      - ./kong.yaml:/home/kong/kong.yml
    ports:
      - "443:8443"
      - "8001:8001"
    restart: always
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "8884:8883"
    volumes: 
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - openamtnetwork
volumes:
    app-volume:
    private-volume:
networks: 
  openamtnetwork:
    driver: "bridge"
